In [1]:
#SC(1,3)
stage1 = Array{Int8,2}([1 1 1;1 0 1;1 1 1])
#stage2 one_side=9
empty2 = zeros(Int8,3,3)
line2_1= hcat(stage1,stage1,stage1)
line2_2= hcat(stage1,empty2,stage1)
stage2 = vcat(line2_1,line2_2,line2_1)
#stage3 one_side=27
empty3 = zeros(Int8,9,9)
line3_1= hcat(stage2,stage2,stage2)
line3_2= hcat(stage2,empty3,stage2)
stage3 = vcat(line3_1,line3_2,line3_1)
#stage4 one_side=81
empty4 = zeros(Int8,27,27)
line4_1= hcat(stage3,stage3,stage3)
line4_2= hcat(stage3,empty4,stage3)
stage4 = vcat(line4_1,line4_2,line4_1)
#stage5 one_side=243
empty5 = zeros(Int8,81,81)
line5_1= hcat(stage4,stage4,stage4)
line5_2= hcat(stage4,empty5,stage4)
stage5 = vcat(line5_1,line5_2,line5_1)
#stage6
empty6 = zeros(Int8,243,243)
line6_1= hcat(stage5,stage5,stage5)
line6_2= hcat(stage5,empty6,stage5)
stage6 = vcat(line6_1,line6_2,line6_1)
#stage7
empty7 = zeros(Int8,729,729)
line7_1= hcat(stage6,stage6,stage6)
line7_2= hcat(stage6,empty7,stage6)
stage7 = vcat(line7_1,line7_2,line7_1)
#stage8
empty8 = zeros(Int8,729*3,729*3)
line8_1= hcat(stage7,stage7,stage7)
line8_2= hcat(stage7,empty8,stage7)
stage8 = vcat(line8_1,line8_2,line8_1)
#stage9
empty9 = zeros(Int8,729*9,729*9)
line9_1= hcat(stage8,stage8,stage8)
line9_2= hcat(stage8,empty9,stage8)
stage9 = vcat(line9_1,line9_2,line9_1)
#stage7
empty10 = zeros(Int8,729*27,729*27)
line10_1= hcat(stage9,stage9,stage9)
line10_2= hcat(stage9,empty10,stage9)
stage10 = vcat(line10_1,line10_2,line10_1)
######
stage = copy(stage3)

27×27 Array{Int8,2}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  0  1  1  0  1  1  0  1  1  0  1  1     1  0  1  1  0  1  1  0  1  1  0  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  0  0  0  1  1  1  1  1  1  0     1  1  1  1  1  1  0  0  0  1  1  1
 1  0  1  0  0  0  1  0  1  1  0  1  0     1  0  1  1  0  1  0  0  0  1  0  1
 1  1  1  0  0  0  1  1  1  1  1  1  0  …  1  1  1  1  1  1  0  0  0  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  0  1  1  0  1  1  0  1  1  0  1  1     1  0  1  1  0  1  1  0  1  1  0  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1  0  0  0  0     0  0  0  1  1  1  1  1  1  1  1  1
 1  0  1  1  0  1  1  0  1  0  0  0  0  …  0  0  0  1  0  1  1  0  1  1  0  1
 1  1  1  1  1  1  1  1  1  0  0  0  0     0  0  0  1  1  1  1  1  1  1  1  1
 1  1  1  0  0  0  1  1  1  0  0  0  0     

In [1]:
#SC(4,2)
stage1 = Array{Int8,2}([1 1 1 1;1 0 0 1;1 0 0 1; 1 1 1 1])
#stage2 one_side=9
empty2 = zeros(Int8,4,4)
line2_1= hcat(stage1,stage1,stage1,stage1)
line2_2= hcat(stage1,empty2,empty2,stage1)
stage2 = vcat(line2_1,line2_2,line2_2,line2_1)#16
#stage3
empty3 = zeros(Int8,16,16)
line3_1= hcat(stage2,stage2,stage2,stage2)
line3_2= hcat(stage2,empty3,empty3,stage2)
stage3 = vcat(line3_1,line3_2,line3_2,line3_1)#64
#stage4
empty4 = zeros(Int8,64,64)
line4_1= hcat(stage3,stage3,stage3,stage3)
line4_2= hcat(stage3,empty4,empty4,stage3)
stage4 = vcat(line4_1,line4_2,line4_2,line4_1)#256
#stage5
empty5 = zeros(Int8,256,256)
line5_1= hcat(stage4,stage4,stage4,stage4)
line5_2= hcat(stage4,empty5,empty5,stage4)
stage5 = vcat(line5_1,line5_2,line5_2,line5_1)#1024
#stage6
empty6 = zeros(Int8,1024,1024)
line6_1= hcat(stage5,stage5,stage5,stage5)
line6_2= hcat(stage5,empty6,empty6,stage5)
stage6 = vcat(line6_1,line6_2,line6_2,line6_1)#4096
#stage7
empty7 = zeros(Int8,4096,4096)
line7_1= hcat(stage6,stage6,stage6,stage6)
line7_2= hcat(stage6,empty7,empty7,stage6)
stage7 = vcat(line7_1,line7_2,line7_2,line7_1)
###
#empty8 = zeros(Int8,16384,16384)
#line8_1= hcat(stage7,stage7,stage7,stage7)
#line8_2= hcat(stage7,empty8,empty8,stage7)
#stage8 = vcat(line8_1,line8_2,line8_2,line8_1)
############
stage2 = 0
stage3 = 0
stage4 = 0 
stage5 = 0
stage6 = 0
#stage7 = 0
stage = copy(stage7)

16384×16384 Array{Int8,2}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  0  0  1  1  0  0  1  1  0  0  1  1     1  0  0  1  1  0  0  1  1  0  0  1
 1  0  0  1  1  0  0  1  1  0  0  1  1     1  0  0  1  1  0  0  1  1  0  0  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  0  0  0  0  0  0  0  0  1     0  0  0  0  0  0  0  0  1  1  1  1
 1  0  0  1  0  0  0  0  0  0  0  0  1  …  0  0  0  0  0  0  0  0  1  0  0  1
 1  0  0  1  0  0  0  0  0  0  0  0  1     0  0  0  0  0  0  0  0  1  0  0  1
 1  1  1  1  0  0  0  0  0  0  0  0  1     0  0  0  0  0  0  0  0  1  1  1  1
 1  1  1  1  0  0  0  0  0  0  0  0  1     0  0  0  0  0  0  0  0  1  1  1  1
 1  0  0  1  0  0  0  0  0  0  0  0  1     0  0  0  0  0  0  0  0  1  0  0  1
 1  0  0  1  0  0  0  0  0  0  0  0  1  …  0  0  0  0  0  0  0  0  1  0  0  1
 1  1  1  1  0  0  0  0  0  0  0  0  1     0  0  0  0  0  0  0  0  1  1  1  1
 1  1  1  1  1  1  1  1  1  1  1  1  

In [1]:
#SC(5,3)
stage1 = Array{Int8,2}([1 1 1 1 1;1 0 0 0 1;1 0 0 0 1;1 0 0 0 1; 1 1 1 1 1])
#stage2 
empty2 = zeros(Int8,5,5)
line2_1= hcat(stage1,stage1,stage1,stage1,stage1)
line2_2= hcat(stage1,empty2,empty2,empty2,stage1)
stage2 = vcat(line2_1,line2_2,line2_2,line2_2,line2_1)
#stage3 
empty3 = zeros(Int8,25,25)
line3_1= hcat(stage2,stage2,stage2,stage2,stage2)
line3_2= hcat(stage2,empty3,empty3,empty3,stage2)
stage3 = vcat(line3_1,line3_2,line3_2,line3_2,line3_1)
#stage4
empty4 = zeros(Int8,125,125)
line4_1= hcat(stage3,stage3,stage3,stage3,stage3)
line4_2= hcat(stage3,empty4,empty4,empty4,stage3)
stage4 = vcat(line4_1,line4_2,line4_2,line4_2,line4_1)
#stage5
empty5 = zeros(Int8,625,625)
line5_1= hcat(stage4,stage4,stage4,stage4,stage4)
line5_2= hcat(stage4,empty5,empty5,empty5,stage4)
stage5 = vcat(line5_1,line5_2,line5_2,line5_2,line5_1)
#stage6
empty6 = zeros(Int8,3125,3125)
line6_1= hcat(stage5,stage5,stage5,stage5,stage5)
line6_2= hcat(stage5,empty6,empty6,empty6,stage5)
stage6 = vcat(line6_1,line6_2,line6_2,line6_2,line6_1)
#stage7
#empty7 = zeros(Int8,3125*5,3125*5)
#line7_1= hcat(stage6,stage6,stage6,stage6,stage6)
#line7_2= hcat(stage6,empty7,empty7,empty7,stage6)
#stage7 = vcat(line7_1,line7_2,line7_2,line7_2,line7_1)
########
stage2 = 0
stage3 = 0
stage4 = 0 
stage5 = 0
#stage6 = 0
stage = copy(stage6)

15625×15625 Array{Int8,2}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  0  0  0  1  1  0  0  0  1  1  0  0     0  1  1  0  0  0  1  1  0  0  0  1
 1  0  0  0  1  1  0  0  0  1  1  0  0     0  1  1  0  0  0  1  1  0  0  0  1
 1  0  0  0  1  1  0  0  0  1  1  0  0     0  1  1  0  0  0  1  1  0  0  0  1
 1  1  1  1  1  1  1  1  1  1  1  1  1     1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  1  1  1  1  1
 1  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  1  0  0  0  1
 1  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  1  0  0  0  1
 1  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  1  0  0  0  1
 1  1  1  1  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  1  1  1  1  1
 1  1  1  1  1  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  1  1  1  1  1
 1  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  1  0  0  0  1
 1  0  0  0  1  0  0  0  0  0  0  0  

In [30]:
#SC(6,4)
stage1 = Array{Int8,2}([1 1 1 1 1 1;1 0 0 0 0 1;1 0 0 0 0 1;1 0 0 0 0 1;1 0 0 0 0 1;1 1 1 1 1 1])
#stage2 
empty2 = zeros(Int8,6,6)
line2_1= hcat(stage1,stage1,stage1,stage1,stage1,stage1)
line2_2= hcat(stage1,empty2,empty2,empty2,empty2,stage1)
stage2 = vcat(line2_1,line2_2,line2_2,line2_2,line2_2,line2_1)
#stage3
empty3 = zeros(Int8,36,36)
line3_1= hcat(stage2,stage2,stage2,stage2,stage2,stage2)
line3_2= hcat(stage2,empty3,empty3,empty3,empty3,stage2)
stage3 = vcat(line3_1,line3_2,line3_2,line3_2,line3_2,line3_1)
#stage4
empty4 = zeros(Int8,216,216)
line4_1= hcat(stage3,stage3,stage3,stage3,stage3,stage3)
line4_2= hcat(stage3,empty4,empty4,empty4,empty4,stage3)
stage4 = vcat(line4_1,line4_2,line4_2,line4_2,line4_2,line4_1)
#stage5
empty5 = zeros(Int8,1296,1296)
line5_1= hcat(stage4,stage4,stage4,stage4,stage4,stage4)
line5_2= hcat(stage4,empty5,empty5,empty5,empty5,stage4)
stage5 = vcat(line5_1,line5_2,line5_2,line5_2,line5_2,line5_1)
#stage6
#empty6 = zeros(Int8,7776,7776)
#line6_1= hcat(stage5,stage5,stage5,stage5,stage5,stage5)
#line6_2= hcat(stage5,empty6,empty6,empty6,empty6,stage5)
#stage6 = vcat(line6_1,line6_2,line6_2,line6_2,line6_2,line6_1)
stage2 = 0
stage3 = 0
stage4 = 0 
#stage5 = 0
stage = copy(stage5)

7776×7776 Array{Int8,2}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  0  0  0  0  1  1  0  0  0  0  1  1     1  0  0  0  0  1  1  0  0  0  0  1
 1  0  0  0  0  1  1  0  0  0  0  1  1     1  0  0  0  0  1  1  0  0  0  0  1
 1  0  0  0  0  1  1  0  0  0  0  1  1     1  0  0  0  0  1  1  0  0  0  0  1
 1  0  0  0  0  1  1  0  0  0  0  1  1     1  0  0  0  0  1  1  0  0  0  0  1
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  0  0  0  0  0  0  0     0  0  0  0  0  0  1  1  1  1  1  1
 1  0  0  0  0  1  0  0  0  0  0  0  0     0  0  0  0  0  0  1  0  0  0  0  1
 1  0  0  0  0  1  0  0  0  0  0  0  0     0  0  0  0  0  0  1  0  0  0  0  1
 1  0  0  0  0  1  0  0  0  0  0  0  0     0  0  0  0  0  0  1  0  0  0  0  1
 1  0  0  0  0  1  0  0  0  0  0  0  0  …  0  0  0  0  0  0  1  0  0  0  0  1
 1  1  1  1  1  1  0  0  0  0  0  0  0     0  0  0  0  0  0  1  1  1  1  1  1
 1  1  1  1  1  1  0  0  0  0  0  0  0 

In [2]:
function x_koteitan(x,n)
    if n >= x >= 1.0 
        return x
    elseif x < 1.0
        return x = 1
    elseif x > n
        return x = n
    end
end

function y_koteitan(y,n)
    if n >= y >= 1.0 
        return y
    elseif y < 1.0
        return y = 1
    elseif y > n
        return y = n
    end
end
#y_koteitan(3,3)

y_koteitan (generic function with 1 method)

In [3]:
#メイン計算
function random_walk(array)
    #s=5;stage = 6
    n = 5^6
    #t+1秒の配列を現在の配列とする
    present = zeros(Int64,1,2)
    present[1,:] = copy(array)
    #x,y方向の変位を収納する箱
    delta   = zeros(Int64,1,2)
    #x,y,z方向をランダムに指定するため
    delta_index = rand(UnitRange{Int8}(1:2))#1ならｘ、２ならy
    #変位を収納する
    if rand(UnitRange{Int8}(0:1)) == 0
        delta[delta_index] = 1
    else
        delta[delta_index] = -1
    end
    
    #t+1秒後の座標
    next_present = present + delta
    
    #メンガーのスポンジの座標に変換、且つ周期境界条件
    #x = ((next_present[1]%n)+n-1)%n +1
    #y = ((next_present[2]%n)+n-1)%n +1
    x = x_koteitan(next_present[1],n)
    y = y_koteitan(next_present[2],n)
    #固定端条件
    if stage[x,y]==1
        final_present=[x y]
    else
        final_present = copy(present)
    end
    
    return final_present
end

random_walk (generic function with 1 method)

In [4]:
using ProgressMeter
function iter( time, loop)
    stage = 6
    mark = 5^(stage-1)
    count_0 = 0
    count_1 = 0
    count_2 = 0
    count_3 = 0
    count_4 = 0
    count_5 = 0
    count_6 = 0
    count_7 = 0
    count_8 = 0
    p = Progress(loop)
    array = zeros(Int64,1,2)
    for i in 1:loop
        array = [mark mark]
        for t in 0:time
            if t == 0
                array = [mark mark]
            else
                array = copy(random_walk(array)) 
            end
            #println(t,array)
            if t == 4 && array==[mark mark]
                count_0 += 1
            elseif t == 4^2 && array==[mark mark]
                count_1 += 1
            elseif t == 4^3 && array==[mark mark]
                count_2 += 1
            elseif t == 4^4 && array==[mark mark]
                count_3 += 1
            elseif t == 4^5 && array==[mark mark]
                count_4 += 1
            elseif t == 4^6 && array==[mark mark]
                count_5 += 1
            elseif t == 4^7 && array==[mark mark]
                count_6 += 1
            elseif t == 4^8 && array==[mark mark]
                count_7 += 1
            #elseif t == 4^9 && array==[mark mark]
            #    count_8 += 1 
            end
            #println(array)
            
            
            
        end
        next!(p)
    end
    println("stage6_5_3")
    println("t=4:", count_0,"\n","t=4**2:",count_1,"\n","t=4**3:",count_2,"\n","t=4**4:",count_3)
    println("t=4**5:",count_4,"\n","t=4**6:",count_5,"\n","t=4**7:",count_6,"\n","t=4**8:",count_7)
    println("t=4**9:", count_8 )
    #println("t=6:",count_0,"\n","t=6**2:",count_1,"\n","t=6**3:",count_2,"\n","t=6**4:",count_3)
    #println("t=6**5:",count_4,"\n","t=6**6:",count_5,"\n","t=6**7:",count_6)#,"\n","t=6**8:",count_7)
    #println("t=4**9:",count_8)
end

iter (generic function with 1 method)

In [ ]:
iter(4^8, 10000)

Progress:   5%|██                                       |  ETA: 0:40:44

In [7]:
n=27
function prob()
    p = zeros(Float64,n,n)
    for x=1:n, y=1:n
        if stage[x,y] == 1
            p[x,y] = 0.2
        else
            continue
        end
    end
    return p
end

prob (generic function with 1 method)

In [17]:
#For plot
using ProgressMeter
using LinearAlgebra
using Plots
gr()
function iter(time)
    array = ones(Int64,1,2)
    anim = @animate for t in 0:time
        p = copy(prob())
        if t == 0
            array = ones(Int64,1,2)
        else
            array = copy(random_walk(array)) 
        end

        #println(array[1])#原点に戻ったら色をつける
        if array==[1 1]
            p[1,1]=0.5
        else
            p[array[1],array[2]]=1
        end
        
        for x in 1:n, y in 1:n
            if p[x,y]==0
                p[x,y]= -0.05
            else
                continue
            end
        end
        heatmap(p,aspect_ratio=1,cbar=false,cbar_lims=(-0.05,1))#,dpi=300)
    end
    return gif(anim,fps=20)
end
iter(300)

┌ Info: Saved animation to 
│   fn = C:\Users\reisa\tmp.gif
└ @ Plots C:\JuliaPkg\packages\Plots\y6yik\src\animation.jl:90


Plots.AnimatedGif("C:\\Users\\reisa\\tmp.gif")

In [8]:
mark = 4^(8-1)
array = zeros(Int64,1,2)
array = [mark mark]

1×2 Array{Int64,2}:
 16384  16384